# Generated by Django 5.2.14 on 2026-05-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_type', models.CharField(choices=[('CLASS', 'Class'), ('ASSIGNMENT', 'Assignment'), ('EXAM', 'Exam'), ('HOLIDAY', 'Holiday')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='batches.batch')),
            ],
            options={
                'ordering': ['session_date', 'id'],
            },
        ),
    ]
